import type { Space, Event, Chef } from "./types";

function unsplash(id: string) {
  return `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1400&q=80`;
}

// Real Blanked photography (public/images) — low-exposure interiors.
export const heroImages = [
  "/images/space-brick-loft.jpg?v=3",
  "/images/space-dark-dining.jpg?v=3",
  "/images/space-timber-lounge.jpg?v=3",
  "/images/space-night-terrace.jpg?v=3",
  "/images/space-bar-shelves.jpg?v=3",
];

export const spaces: Space[] = [
  {
    slug: "the-loft-at-flinders-lane",
    name: "The Loft at Flinders Lane",
    suburb: "CBD",
    type: "Event",
    capacity: 80,
    sqft: 2200,
    dailyRate: 1800,
    weeklyRate: 9500,
    minBookingDuration: "1 day",
    description:
      "A raw, industrial loft space in the heart of Flinders Lane with exposed brick, skylights, and a flexible open floor plan — perfect for intimate dining experiences.",
    whatCanYouDo:
      "You will have full access to the event space and kitchen during your booked hours, and are welcome to bring your own equipment and staff. The space is yours to configure as you see fit — seating, stations, and layout can all be adjusted. AV equipment is available for your use. You keep all food and beverage revenue generated during your event. The space must be returned to its original condition at the end of your booking, and any breakages will be charged to the operator.",
    availability:
      "This venue operates as a café from 9am–3pm, Monday to Friday. Outside these hours, the space is fully vacant and available for hire on evenings and weekends. Hirers are also welcome to share the kitchen during opening hours for prep.",
    amenities: ["kitchen", "bar", "seating", "wifi", "AV equipment"],
    kitchenFacilities: ["Full commercial kitchen"],
    equipmentIncluded: ["Tables and chairs", "AV equipment"],
    images: [
      "/images/space-brick-loft.jpg?v=3",
      unsplash("photo-1517248135467-4c7edcad34c4"),
      unsplash("photo-1552566626-52f8b828add9"),
    ],
    featured: true,
    spaceRules: [
      "No smoking indoors",
      "Music must end by 11pm",
      "Space returned to original condition",
    ],
    reviews: [
      {
        author: "Mia Thornton",
        authorRole: "Talent / Supper Club Host",
        rating: 5,
        date: "May 2026",
        text: "Ran a two-night supper club here and the room did half the work for me. Kitchen is genuinely commercial-grade and the landlord was easy about bump-in.",
      },
      {
        author: "Jordan Reyes",
        authorRole: "Talent",
        rating: 5,
        date: "April 2026",
        text: "Beautiful raw space, great light for content, zero drama on the day. Would book again without thinking.",
      },
      {
        author: "Priya Chandra",
        authorRole: "Talent / Brand Founder",
        rating: 4,
        date: "February 2026",
        text: "Loved the room. Only note is load-in via the laneway takes a while — plan an extra half hour.",
      },
    ],
  },
  {
    slug: "gertrude-street-bistro",
    name: "Gertrude Street Bistro",
    suburb: "Fitzroy",
    type: "Restaurant",
    capacity: 60,
    sqft: 1500,
    dailyRate: 1500,
    weeklyRate: 8000,
    monthlyRate: 28000,
    minBookingDuration: "1 week",
    description:
      "A warm, brick-walled bistro on Gertrude Street with a full working kitchen and an established regular crowd looking for something new.",
    whatCanYouDo:
      "Take over the full dining room and kitchen for your residency. Existing bookings system, POS, and front-of-house staff can be made available on request. Keep 100% of food and beverage revenue.",
    availability:
      "This venue operates as a bistro under its own brand most nights of the week. Residencies take over the full dining room and kitchen for a minimum one-week block, so the space isn't available for single-day bookings.",
    amenities: ["kitchen", "bar", "seating", "wifi"],
    kitchenFacilities: ["Full commercial kitchen", "Coffee equipment"],
    equipmentIncluded: ["Tables and chairs", "Bar setup", "POS"],
    images: [
      "/images/space-dark-dining.jpg?v=3",
      unsplash("photo-1592861956120-e524fc739696"),
      unsplash("photo-1600891964092-4316c288032e"),
    ],
    featured: true,
    spaceRules: ["No smoking indoors", "Kitchen closed by 11:30pm"],
    reviews: [
      {
        author: "Tom Whitfield",
        authorRole: "Talent",
        rating: 5,
        date: "June 2026",
        text: "A week-long residency that ran like clockwork. The regulars showed up, the kitchen never missed, and the handover was painless.",
      },
      {
        author: "Priya Chandra",
        authorRole: "Talent / Brand Founder",
        rating: 5,
        date: "March 2026",
        text: "The existing crowd is the real asset here — we sold out two nights on their foot traffic alone.",
      },
    ],
  },
  {
    slug: "smith-street-kitchen",
    name: "Smith Street Kitchen",
    suburb: "Collingwood",
    type: "Kitchen only",
    capacity: 20,
    sqft: 800,
    dailyRate: 800,
    weeklyRate: 4200,
    minBookingDuration: "1 day",
    description:
      "A compact prep kitchen and dining nook ideal for supper clubs, tasting menus, and collaborative pop-ups with other talent.",
    whatCanYouDo:
      "Share the space with one other operator per booking window. Prep kitchen access included, plus a small dining area for up to 20 guests.",
    availability:
      "This is a shared prep kitchen used by multiple operators across the week. Booking windows are coordinated with a co-operator sharing the same slot, so exact days and hours are confirmed at the time of booking.",
    amenities: ["kitchen", "seating", "wifi"],
    kitchenFacilities: ["Prep kitchen only"],
    equipmentIncluded: ["Tables and chairs"],
    images: [
      unsplash("photo-1552566626-52f8b828add9"),
      unsplash("photo-1466978913421-dad2ebd01d17"),
    ],
    spaceRules: ["Shared space — coordinate with co-operator", "Clean as you go"],
    reviews: [
      {
        author: "Amara Osei",
        authorRole: "Talent / Caterer",
        rating: 4,
        date: "May 2026",
        text: "Tight but well thought out. Perfect for a 16-cover tasting menu — wouldn't push it past 20.",
      },
    ],
  },
  {
    slug: "little-collins-speakeasy",
    name: "Little Collins Speakeasy",
    suburb: "CBD",
    type: "Bar",
    capacity: 45,
    sqft: 1100,
    dailyRate: 950,
    weeklyRate: 5000,
    minBookingDuration: "1 day",
    description:
      "Moody laneway bar with arched windows and a full bar setup, ready for a late-night residency or one-off event.",
    whatCanYouDo:
      "Full bar and small kitchen access. Ideal for cocktail-led pop-ups, tasting nights and small-format dinners.",
    availability:
      "This venue operates as a licensed bar most evenings. Daytime and early-evening slots are generally available for hire, with bookings needing to wrap by midnight in line with the venue's music curfew.",
    amenities: ["bar", "seating", "wifi", "AV equipment"],
    kitchenFacilities: ["No kitchen", "Coffee equipment"],
    equipmentIncluded: ["Bar setup", "AV equipment"],
    images: [
      "/images/space-timber-lounge.jpg?v=3",
      "/images/space-bar-shelves.jpg?v=3",
      unsplash("photo-1533777857889-4be7c70b33f7"),
    ],
    spaceRules: ["Licensed venue — RSA required", "Music must end by midnight"],
    reviews: [
      {
        author: "Jordan Reyes",
        authorRole: "Talent",
        rating: 5,
        date: "June 2026",
        text: "My noodle bar has popped up here three times now. Late crowd is built in, bar staff know the drill.",
      },
      {
        author: "Leo Nakamura",
        authorRole: "Talent / Brand Founder",
        rating: 4,
        date: "January 2026",
        text: "Great vibe, no kitchen though — you're prepping off-site. Know that going in and it's a brilliant room.",
      },
    ],
  },
  {
    slug: "brunswick-yard-market",
    name: "Brunswick Yard Market",
    suburb: "Brunswick",
    type: "Market",
    capacity: 30,
    sqft: 400,
    dailyRate: 450,
    minBookingDuration: "1 day",
    description:
      "An open-air courtyard spot with market stall infrastructure, great foot traffic on weekends.",
    whatCanYouDo:
      "Set up a stall for a single trading day. Power and water access included. Bring your own marquee and equipment.",
    availability:
      "This is an open-air market courtyard booked one trading day at a time, most popular on weekends when foot traffic peaks. Stalls must be packed down the same day — there's no overnight storage.",
    amenities: ["seating", "parking"],
    kitchenFacilities: ["No kitchen"],
    equipmentIncluded: ["None"],
    images: [
      unsplash("photo-1533777857889-4be7c70b33f7"),
      unsplash("photo-1555396273-367ea4eb4db5"),
    ],
    spaceRules: ["Pack down same day", "No open flames without approval"],
    reviews: [
      {
        author: "Leo Nakamura",
        authorRole: "Talent / Brand Founder",
        rating: 5,
        date: "April 2026",
        text: "Where the brand started. Saturday foot traffic is unreal — bring more stock than you think you need.",
      },
    ],
  },
  {
    slug: "richmond-rooftop",
    name: "Richmond Rooftop",
    suburb: "Richmond",
    type: "Event",
    capacity: 120,
    sqft: 3000,
    dailyRate: 2500,
    weeklyRate: 13000,
    minBookingDuration: "1 day",
    description:
      "A sprawling rooftop with skyline views, built for large-format events, brand activations and long lunch residencies.",
    whatCanYouDo:
      "Full rooftop access including bar, DJ booth, and covered dining area. Ideal for launch events and large pop-up dinners.",
    availability:
      "This rooftop is available for single and multi-day bookings year-round, weather permitting. As an open-air space, a wet-weather contingency plan is required before confirming a date, and amplified music must end by 11pm.",
    amenities: ["bar", "seating", "wifi", "AV equipment"],
    kitchenFacilities: ["Prep kitchen only"],
    equipmentIncluded: ["Tables and chairs", "Bar setup", "AV equipment"],
    images: [
      "/images/space-night-terrace.jpg?v=3",
      unsplash("photo-1508615039623-a25605d2b022"),
    ],
    spaceRules: ["Weather contingency required", "Music must end by 11pm"],
    reviews: [
      {
        author: "Mia Thornton",
        authorRole: "Talent / Supper Club Host",
        rating: 5,
        date: "March 2026",
        text: "Golden hour up here is worth the rate on its own. We shot an entire campaign during service.",
      },
      {
        author: "Amara Osei",
        authorRole: "Talent / Caterer",
        rating: 4,
        date: "February 2026",
        text: "Stunning venue for events. Have a wet-weather plan locked before you commit to a date.",
      },
    ],
  },
  {
    slug: "carlton-corner-cafe",
    name: "Carlton Corner Cafe",
    suburb: "Carlton",
    type: "Cafe",
    capacity: 35,
    sqft: 900,
    dailyRate: 700,
    weeklyRate: 3800,
    monthlyRate: 13500,
    minBookingDuration: "3 days",
    description:
      "A daylight-filled corner cafe with a loyal breakfast crowd, available for weekday residencies.",
    whatCanYouDo:
      "Run breakfast and lunch service using the existing kitchen and coffee setup. Great for hospitality talent testing a daytime concept.",
    availability:
      "This venue operates as a cafe serving breakfast and lunch on weekdays. It's available for residencies of three days or more, with kitchen access until 3pm each day — evenings and weekends are not available.",
    amenities: ["kitchen", "seating", "wifi"],
    kitchenFacilities: ["Full commercial kitchen", "Coffee equipment"],
    equipmentIncluded: ["Tables and chairs", "POS"],
    images: [
      unsplash("photo-1466978913421-dad2ebd01d17"),
      unsplash("photo-1517248135467-4c7edcad34c4"),
    ],
    spaceRules: ["Available weekdays only", "Kitchen closed by 3pm"],
    reviews: [
      {
        author: "Tom Whitfield",
        authorRole: "Talent",
        rating: 4,
        date: "May 2026",
        text: "Ideal weekday test bed. Uni crowd is honest feedback — if it sells here, it sells anywhere.",
      },
    ],
  },
  {
    slug: "st-kilda-beach-house",
    name: "St Kilda Beach House",
    suburb: "St Kilda",
    type: "Event",
    capacity: 90,
    sqft: 2000,
    dailyRate: 1200,
    weeklyRate: 6500,
    minBookingDuration: "1 day",
    description:
      "Beachside function space with a wraparound deck, ten minutes from the city — a favourite for weekend supper clubs.",
    whatCanYouDo:
      "Full access to the dining room, deck, and kitchen. Ocean views make this a strong pick for seasonal or celebratory pop-ups.",
    availability:
      "This beachside function space is available for single-day and weekend bookings throughout the week. As it sits close to residential neighbours, a sound curfew of 10pm applies to all bookings.",
    amenities: ["kitchen", "bar", "seating", "parking"],
    kitchenFacilities: ["Full commercial kitchen"],
    equipmentIncluded: ["Tables and chairs", "Bar setup"],
    images: [
      unsplash("photo-1508615039623-a25605d2b022"),
      unsplash("photo-1555992336-fb0d29498b13"),
    ],
    spaceRules: ["No smoking indoors", "Sound curfew 10pm"],
    reviews: [],
  },
];

export const chefs: Chef[] = [
  {
    slug: "mia-thornton",
    name: "Mia Thornton",
    role: "Talent / Supper Club Host",
    bio: "Mia has spent the past six years cooking across Melbourne's best kitchens before striking out on her own with a rotating supper club focused on modern Australian produce. She's run pop-ups from Fitzroy to the Yarra Valley and is known for menus that change with the season and never repeat.",
    quote: "Blanked let me stop chasing landlords and start cooking.",
    portrait: unsplash("photo-1494790108377-be9c29b29330"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Restaurant", "Kitchen only"],
    locationPreferences: ["Fitzroy", "Collingwood", "CBD"],
    featured: true,
  },
  {
    slug: "leo-nakamura",
    name: "Leo Nakamura",
    role: "Talent / Brand Founder",
    bio: "Leo runs a Japanese-Australian fusion brand that started as a market stall and has grown into one of the city's most talked-about pop-ups. He's cooked residencies in three states and is currently focused on bringing his concept to a permanent home in Melbourne.",
    quote: "Every space we've booked through Blanked has come with zero drama.",
    portrait: unsplash("photo-1595273670150-bd0c3c392e46"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Market", "Restaurant"],
    locationPreferences: ["Brunswick", "CBD"],
    featured: true,
  },
  {
    slug: "amara-osei",
    name: "Amara Osei",
    role: "Talent / Caterer",
    bio: "Amara's West African-inspired dinners have built a cult following through word of mouth alone. She's now scaling up with residencies and larger event bookings, bringing her food to rooms that seat sixty instead of six.",
    quote: "Landlords take me seriously the moment I mention Blanked.",
    portrait: unsplash("photo-1524504388940-b1c1722653e1"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Event", "Restaurant"],
    locationPreferences: ["Richmond", "St Kilda"],
    featured: true,
  },
  {
    slug: "tom-whitfield",
    name: "Tom Whitfield",
    role: "Talent",
    bio: "Tom trained in fine dining before pivoting to casual, produce-led pop-ups. He runs short residencies of one to two weeks at a time, testing new menus in front of a live audience before deciding what sticks.",
    quote: "I book, I cook, I move on to the next room.",
    portrait: unsplash("photo-1500648767791-00dcc994a43e"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Restaurant"],
    locationPreferences: ["Carlton", "CBD"],
    featured: true,
  },
  {
    slug: "priya-chandra",
    name: "Priya Chandra",
    role: "Talent / Brand Founder",
    bio: "Priya's modern Indian dining concept has run pop-ups across six Melbourne suburbs in the last year. She's known for pairing regional Indian dishes with natural wine.",
    quote: "The booking flow is faster than texting a landlord back and forth.",
    portrait: unsplash("photo-1544005313-94ddf0286df2"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Kitchen only", "Restaurant"],
    locationPreferences: ["Fitzroy", "Brunswick"],
  },
  {
    slug: "jordan-reyes",
    name: "Jordan Reyes",
    role: "Talent",
    bio: "Jordan's late-night noodle bar concept started as a one-off collab and has since become a recurring residency, moving between speakeasies and laneway bars across the city.",
    quote: "Blanked found me spaces I never would have known existed.",
    portrait: unsplash("photo-1568602471122-7832951cc4c5"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Bar", "Kitchen only"],
    locationPreferences: ["CBD", "Richmond"],
  },
  {
    slug: "sofia-marchetti",
    name: "Sofia Marchetti",
    role: "Talent / Pastry Chef",
    bio: "Sofia spent years perfecting laminated pastry in Melbourne's top bakeries before launching her own dessert-only pop-up series. She partners with cafes and bars after hours, turning empty kitchens into late-night patisserie counters.",
    quote: "Blanked turns a dead kitchen at 9pm into a queue out the door.",
    portrait: unsplash("photo-1573497019940-1c28c88b4f3e"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Kitchen only", "Restaurant"],
    locationPreferences: ["Fitzroy", "CBD"],
    featured: true,
  },
  {
    slug: "daniel-kwan",
    name: "Daniel Kwan",
    role: "Talent / Bartender",
    bio: "Daniel has built cocktail programs for some of the city's busiest bars and now runs a rotating pop-up bar concept, taking over unused venues for one-night takeovers built around a single spirit or theme.",
    quote: "I don't need a lease to build a bar program — just a night and a good room.",
    portrait: unsplash("photo-1519085360753-af0119f7cbe7"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Bar", "Event"],
    locationPreferences: ["CBD", "Collingwood"],
    featured: true,
  },
  {
    slug: "isla-fitzgerald",
    name: "Isla Fitzgerald",
    role: "Talent / Baker",
    bio: "Isla's sourdough and viennoiserie pop-ups started as a weekend stall and have grown into a waitlist-only bake sale that moves between cafes across the inner north.",
    quote: "Blanked found me a proper kitchen instead of my home oven at 4am.",
    portrait: unsplash("photo-1580489944761-15a19d654956"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Market", "Kitchen only"],
    locationPreferences: ["Brunswick", "Fitzroy"],
    featured: true,
  },
  {
    slug: "noah-bennett",
    name: "Noah Bennett",
    role: "Talent",
    bio: "Noah runs a late-night noodle and dumpling pop-up that's moved through bars, laneways, and empty shopfronts across the city, chasing whatever room has a working stove.",
    quote: "Blanked is the only reason I stopped cold-emailing venue owners.",
    portrait: unsplash("photo-1610088441520-4352457e7095"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Restaurant", "Kitchen only"],
    locationPreferences: ["Richmond", "CBD"],
    featured: true,
  },
  {
    slug: "maya-delacroix",
    name: "Maya Delacroix",
    role: "Talent / Sommelier",
    bio: "Maya pairs natural wine with short residencies at restaurants between tenants, building one-off tasting menus around whatever's in season and whoever's kitchen she's borrowing.",
    quote: "Every space on Blanked already knows how to say yes to a wine night.",
    portrait: unsplash("photo-1607746882042-944635dfe10e"),
    instagram: "https://instagram.com",
    spaceTypePreferences: ["Restaurant", "Event"],
    locationPreferences: ["St Kilda", "CBD"],
    featured: true,
  },
];

export const events: Event[] = [
  {
    slug: "mia-thornton-winter-supper-club",
    name: "Winter Supper Club",
    chefSlug: "mia-thornton",
    spaceSlug: "the-loft-at-flinders-lane",
    date: "2026-08-04",
    time: "7:00pm",
    suburb: "CBD",
    price: 145,
    status: "Available",
    images: ["/images/food-plated-duo.jpg?v=3"],
    description:
      "A five-course seasonal menu built around Victorian winter produce, hosted in the raw industrial space at The Loft at Flinders Lane.",
    ticketUrl: "https://instagram.com",
  },
  {
    slug: "leo-nakamura-market-day",
    name: "Nakamura Market Day",
    chefSlug: "leo-nakamura",
    spaceSlug: "brunswick-yard-market",
    date: "2026-07-19",
    time: "10:00am",
    suburb: "Brunswick",
    price: "Free",
    status: "Available",
    images: [unsplash("photo-1555396273-367ea4eb4db5")],
    description:
      "A casual weekend market stall serving Leo's Japanese-Australian fusion snacks. Free entry, food available for purchase.",
    ticketUrl: "https://instagram.com",
  },
  {
    slug: "amara-osei-residency-launch",
    name: "Amara Osei Residency Launch",
    chefSlug: "amara-osei",
    spaceSlug: "richmond-rooftop",
    date: "2026-07-26",
    time: "6:30pm",
    suburb: "Richmond",
    price: 120,
    status: "Selling Fast",
    images: ["/images/food-prawn.jpg?v=3"],
    description:
      "Amara opens a two-week rooftop residency with a launch night set menu inspired by West African home cooking.",
    ticketUrl: "https://instagram.com",
  },
  {
    slug: "tom-whitfield-test-kitchen",
    name: "Test Kitchen: Vol. 3",
    chefSlug: "tom-whitfield",
    spaceSlug: "carlton-corner-cafe",
    date: "2026-08-12",
    time: "12:00pm",
    suburb: "Carlton",
    price: 65,
    status: "Available",
    images: [unsplash("photo-1466978913421-dad2ebd01d17")],
    description:
      "Tom trials three new dishes for lunch service ahead of his next residency. Limited covers.",
    ticketUrl: "https://instagram.com",
  },
  {
    slug: "priya-chandra-natural-wine-night",
    name: "Natural Wine & Regional Plates",
    chefSlug: "priya-chandra",
    spaceSlug: "gertrude-street-bistro",
    date: "2026-07-22",
    time: "7:30pm",
    suburb: "Fitzroy",
    price: 95,
    status: "Sold Out",
    images: [unsplash("photo-1517248135467-4c7edcad34c4")],
    description:
      "A six-dish regional Indian tasting menu paired with a natural wine list curated for the evening.",
    ticketUrl: "https://instagram.com",
  },
  {
    slug: "jordan-reyes-late-night-noodles",
    name: "Late Night Noodles",
    chefSlug: "jordan-reyes",
    spaceSlug: "little-collins-speakeasy",
    date: "2026-08-01",
    time: "9:00pm",
    suburb: "CBD",
    price: 40,
    status: "Available",
    images: ["/images/drink-cocktail.jpg?v=3"],
    description:
      "Jordan's late-night noodle bar pops up in the laneway speakeasy for one night only.",
    ticketUrl: "https://instagram.com",
  },
];

export const suburbs = [
  "Fitzroy",
  "Brunswick",
  "Collingwood",
  "CBD",
  "Carlton",
  "Richmond",
  "St Kilda",
  "Other",
];

export const spaceTypes: Space["type"][] = [
  "Restaurant",
  "Bar",
  "Cafe",
  "Event",
  "Retail",
  "Market",
  "Kitchen only",
];

export const mockChefProfile = {
  name: "Mia Thornton",
  photo: chefs[0].portrait,
  bio: chefs[0].bio,
  role: "Owner",
  instagram: chefs[0].instagram,
  spaceTypePreferences: chefs[0].spaceTypePreferences,
  email: "mia@blanked.melbourne",
  website: "https://miathornton.com",
  addressLine: "12 Smith Street",
  addressSuburb: "Fitzroy",
  addressState: "VIC",
  addressPostcode: "3065",
  photos: [
    chefs[0].portrait,
    "/images/food-plated-duo.jpg?v=3",
    "/images/drink-cocktail.jpg?v=3",
  ],
};

export const mockLandlordProfile = {
  name: "Richmond Rooftop Pty Ltd",
  photo: spaces[5].images[0],
  role: "Owner",
  email: "richmond@blanked.melbourne",
  website: "https://richmondrooftop.com.au",
  addressLine: "88 Bridge Road",
  addressSuburb: "Richmond",
  addressState: "VIC",
  addressPostcode: "3121",
  photos: [spaces[5].images[0], spaces[5].images[1]],
};

export const mockCustomerProfile = {
  name: "Alex Chen",
  photo: null as string | null,
  email: "alex.chen@blanked.melbourne",
};
